spring:
  redis:
    password: 123456
    cluster:
      #获取失败,最大重定向次数
      max-redirects: 3
      nodes:
        - 120.55.40.51:7001
        - 120.55.40.51:7002
        - 120.55.40.51:7003
        - 120.55.40.51:7004
        - 120.55.40.51:7005
        - 120.55.40.51:7006
    lettuce:
      pool:
        #连接池最大连接数(使用负值表示没有限制)
        max-active: 8
        #连接池中的最大空闲连接
        max-idle: 1000
        #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-wait: 1000
        #连接池中的最小空闲连接
        min-idle: 0
    timeout: 3000
    redisson:
      config: classpath:redisson-cluster.yml